import { build } from "esbuild";

/**
 * Bundles the diagram webview client into `media/diagram.js`.
 *
 * The client is TypeScript and imports the same viewport module the unit tests
 * exercise, so the behaviour that ships is the behaviour that is tested. A
 * webview cannot resolve workspace packages at runtime, hence the bundle.
 *
 * The output is an IIFE with no imports and no `eval`, which is what the
 * webview's `script-src 'nonce-…'` CSP allows.
 */
await build({
  entryPoints: ["src/webview/client/main.ts"],
  outfile: "media/diagram.js",
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  legalComments: "none",
  banner: {
    js: "// Generated by tools/build-webview.mjs from src/webview/client/main.ts. Do not edit.",
  },
});

console.log("webview client bundled to media/diagram.js");
