import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { diagramStylesheet } from "../dist/webview/diagramHtml.js";

/**
 * Generates the two files the diagram webview loads at runtime.
 *
 * `media/diagram.js` — the client, bundled from TypeScript. It imports the same
 * viewport module the unit tests exercise, so the behaviour that ships is the
 * behaviour that is tested. A webview cannot resolve workspace packages at
 * runtime, hence the bundle. The output is an IIFE with no imports and no
 * `eval`, which is what the webview's `script-src 'nonce-…'` CSP allows.
 *
 * `media/diagram.css` — emitted from `diagramStylesheet()` rather than
 * hand-maintained. The stylesheet used to be a checked-in file that nobody
 * regenerated, so it silently drifted from the function the tests assert on:
 * the tests passed, and the shipped webview was missing every rule added by the
 * change. Generating it here makes drift impossible.
 */
await build({
  entryPoints: ["src/webview/client/main.ts"],
  outfile: "media/diagram.js",
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  legalComments: "none",
  banner: {
    js: "// Generated by tools/build-webview.mjs from src/webview/client/main.ts. Do not edit.",
  },
});

writeFileSync(
  "media/diagram.css",
  `/* Generated by tools/build-webview.mjs from diagramStylesheet(). Do not edit. */\n${diagramStylesheet()}`,
  "utf8",
);

console.log("webview client bundled to media/diagram.js");
console.log("webview stylesheet written to media/diagram.css");
