import { readFileSync } from "node:fs";
import * as path from "node:path";
import { describe, expect, it } from "vitest";
import { diagramStylesheet } from "../src/webview/diagramHtml.js";
import { isDiagramMessage, isWebviewReady } from "../src/webview/protocol.js";

const mediaDir = path.resolve(__dirname, "..", "media");

/**
 * The webview loads `media/diagram.js` and `media/diagram.css` at runtime, but
 * the tests exercise the TypeScript sources. Nothing connects the two unless it
 * is asserted, and it once was not: the stylesheet was a hand-maintained file
 * that stopped matching `diagramStylesheet()`, so an entire slice of layout
 * rules was tested, passed, and never shipped. These tests fail if the built
 * media files drift from the code again.
 */
describe("packaged webview media", () => {
  it("ships the stylesheet the code generates", () => {
    const onDisk = readFileSync(path.join(mediaDir, "diagram.css"), "utf8");
    expect(onDisk).toContain(diagramStylesheet());
  });

  it("ships a generated, import-free client bundle", () => {
    const bundle = readFileSync(path.join(mediaDir, "diagram.js"), "utf8");
    expect(bundle).toContain("Generated by tools/build-webview.mjs");
    // A webview cannot resolve bare imports and the CSP forbids eval; either
    // appearing means the bundle was produced with the wrong settings.
    expect(bundle).not.toMatch(/^\s*import\s/m);
    expect(bundle).not.toMatch(/\beval\(/);
    expect(bundle.length).toBeGreaterThan(1000);
  });
});

describe("diagram layout", () => {
  it("gives the sheet a resolvable full-height chain", () => {
    // Regression: the sheet asked for height:100% while no ancestor had a
    // height, so it collapsed to its 200px min-height. Fit then measured a
    // 200px viewport and drew the diagram, correctly fitted, into a strip at
    // the top of an empty panel. Percentage heights need the whole chain.
    const css = diagramStylesheet();
    expect(css).toMatch(/html,\s*\nbody\.mso-body \{\s*\n\s*height: 100%;/);
    expect(css).toContain(".mso-canvas-shell");
    expect(css).toContain(".mso-sheet-area");
    // A flex column whose items may overflow needs min-height:0 to shrink.
    expect(css.match(/min-height: 0;/g)?.length ?? 0).toBeGreaterThanOrEqual(2);
    expect(css).not.toMatch(/\.mso-sheet \{[^}]*height: 100%/);
  });
});

describe("isDiagramMessage", () => {
  const scene = {
    version: 1,
    type: "diagram/scene",
    payload: {
      svg: "<svg/>",
      content: { width: 10, height: 10 },
      label: "Diagram of M",
      status: "M: 0 components, 0 connections.",
    },
  };

  it("accepts the messages the host actually sends", () => {
    expect(isDiagramMessage(scene)).toBe(true);
    expect(
      isDiagramMessage({ version: 1, type: "diagram/status", payload: { status: "working" } }),
    ).toBe(true);
  });

  it("rejects anything else posted into the frame", () => {
    for (const value of [
      undefined,
      null,
      "diagram/scene",
      42,
      {},
      { ...scene, version: 2 },
      { version: 1, type: "diagram/scene" },
      { version: 1, type: "evil/command", payload: { status: "x" } },
      { ...scene, payload: { ...scene.payload, svg: 123 } },
      { ...scene, payload: { ...scene.payload, content: null } },
      { ...scene, payload: { ...scene.payload, content: { width: "10", height: 10 } } },
    ]) {
      expect(isDiagramMessage(value), JSON.stringify(value ?? null)).toBe(false);
    }
  });

  it("does not throw on a payload that would crash a naive listener", () => {
    // The bug this guards: reading message.payload.svg on a payload-less message
    // throws inside the listener, and the canvas silently stops updating.
    expect(() => isDiagramMessage({ version: 1, type: "diagram/scene" })).not.toThrow();
  });
});

describe("isWebviewReady", () => {
  it("requires the contract version, not just the type", () => {
    expect(isWebviewReady({ version: 1, type: "webview/ready" })).toBe(true);
    expect(isWebviewReady({ type: "webview/ready" })).toBe(false);
    expect(isWebviewReady({ version: 99, type: "webview/ready" })).toBe(false);
    expect(isWebviewReady(null)).toBe(false);
  });
});
