import { readFileSync } from "node:fs";
import * as path from "node:path";
import { describe, expect, it } from "vitest";
import { LAYOUT } from "@modelica-studio/ui";
import { buildDiagramHtml, diagramStylesheet } from "../src/webview/diagramHtml.js";
import { isDiagramMessage, isWebviewReady } from "../src/webview/protocol.js";

const mediaDir = path.resolve(__dirname, "..", "media");

/**
 * The webview loads `media/diagram.js` and `media/diagram.css` at runtime, but
 * the tests exercise the TypeScript sources. Nothing connects the two unless it
 * is asserted, and it once was not: the stylesheet was a hand-maintained file
 * that stopped matching `diagramStylesheet()`, so an entire slice of layout
 * rules was tested, passed, and never shipped. These tests fail if the built
 * media files drift from the code again.
 */
describe("packaged webview media", () => {
  it("ships the stylesheet the code generates", () => {
    const onDisk = readFileSync(path.join(mediaDir, "diagram.css"), "utf8");
    expect(onDisk).toContain(diagramStylesheet());
  });

  it("ships a generated, import-free client bundle", () => {
    const bundle = readFileSync(path.join(mediaDir, "diagram.js"), "utf8");
    expect(bundle).toContain("Generated by tools/build-webview.mjs");
    // A webview cannot resolve bare imports and the CSP forbids eval; either
    // appearing means the bundle was produced with the wrong settings.
    expect(bundle).not.toMatch(/^\s*import\s/m);
    expect(bundle).not.toMatch(/\beval\(/);
    expect(bundle.length).toBeGreaterThan(1000);
  });
});

describe("diagram layout", () => {
  it("gives the sheet a resolvable full-height chain", () => {
    // Regression: the sheet asked for height:100% while no ancestor had a
    // height, so it collapsed to its 200px min-height. Fit then measured a
    // 200px viewport and drew the diagram, correctly fitted, into a strip at
    // the top of an empty panel. Percentage heights need the whole chain.
    const css = diagramStylesheet();
    expect(css).toMatch(/html,\s*\nbody\.mso-body \{\s*\n\s*height: 100%;/);
    expect(css).toContain(".mso-canvas-shell");
    expect(css).toContain(".mso-sheet-area");
    // A flex column whose items may overflow needs min-height:0 to shrink.
    expect(css.match(/min-height: 0;/g)?.length ?? 0).toBeGreaterThanOrEqual(2);
    expect(css).not.toMatch(/\.mso-sheet \{[^}]*height: 100%/);
  });
});

describe("visual spec conformance", () => {
  // docs/04-visual-spec.md is the parity contract with the reference product.
  // Every number it states had no consumer before these tests: LAYOUT was
  // exported and imported nowhere, and the stylesheet defined no rule at all
  // for .mso-tool-rail, .mso-tool, .mso-mode-controls or .mso-status, so the
  // markup shipped those classes entirely unstyled.
  const css = diagramStylesheet();
  const html = buildDiagramHtml({
    cspSource: "vscode-webview://x",
    nonce: "n",
    scriptUri: "diagram.js",
    styleUri: "diagram.css",
    title: "t",
  });

  it("drives the 46px tool rail from the shared layout constant", () => {
    expect(LAYOUT.toolRailWidth).toBe(46);
    expect(css).toContain(`--mso-tool-rail-width: ${LAYOUT.toolRailWidth}px`);
    expect(css).toMatch(/\.mso-tool-rail \{[^}]*width: var\(--mso-tool-rail-width\)/);
  });

  it("floats the rail over the canvas instead of taking flex space", () => {
    // A rail in the flex flow narrows the sheet and shifts the diagram.
    expect(css).toMatch(/\.mso-tool-rail \{[^}]*position: absolute/);
  });

  it("gives the drawing extent a light sheet in every theme", () => {
    // MSL icons and annotation colours are model data and are never
    // theme-remapped, so a themed (dark) sheet hides the model's own strokes.
    expect(css).toContain("--mso-sheet-bg: #ffffff");
    expect(css).toMatch(/\.mso-extent \{[^}]*background-color: var\(--mso-sheet-bg\)/);
    // Outside the extent stays neutral editor background.
    expect(css).toContain("--mso-canvas-bg: var(--vscode-editor-background)");
  });

  it("draws a major and minor grid sized from the scale", () => {
    expect(css).toContain("--mso-grid-major-size");
    expect(css).toContain("--mso-grid-minor-size");
    expect(css).toMatch(/\.mso-extent \{[^}]*background-image:/);
  });

  it("drops the extent shadow in forced colours", () => {
    expect(css).toContain("@media not (forced-colors: active)");
  });

  it("renders the rail groups the spec lists, in order", () => {
    const tools = [...html.matchAll(/data-(?:tool|view-tool)="([a-z-]+)"/g)].map((m) => m[1]);
    expect(tools).toEqual([
      "select",
      "connection",
      "polygon",
      "rectangle",
      "ellipse",
      "text",
      "bitmap",
      "fit",
      "zoom-in",
      "zoom-out",
      "reset",
    ]);
  });

  it("renders two segmented rows top right, not one", () => {
    expect(html).toContain('aria-label="View mode"');
    expect(html).toContain('aria-label="Simulation"');
    const runTools = [...html.matchAll(/data-run-tool="([a-z-]+)"/g)].map((m) => m[1]);
    expect(runTools).toEqual(["route", "run", "run-menu"]);
  });

  it("styles every class the markup ships", () => {
    // The defect this catches: markup carrying a class the stylesheet never
    // mentions renders as unstyled default HTML in production.
    const classes = new Set(
      [...html.matchAll(/class="([^"]+)"/g)].flatMap((m) => m[1].split(/\s+/)),
    );
    for (const name of classes) {
      if (name === "is-active") {
        continue;
      }
      expect(css, `.${name} is in the markup but has no rule`).toContain(`.${name}`);
    }
  });
});

describe("isDiagramMessage", () => {
  const scene = {
    version: 1,
    type: "diagram/scene",
    payload: {
      svg: "<svg/>",
      content: { width: 10, height: 10 },
      label: "Diagram of M",
      status: "M: 0 components, 0 connections.",
    },
  };

  it("accepts the messages the host actually sends", () => {
    expect(isDiagramMessage(scene)).toBe(true);
    expect(
      isDiagramMessage({ version: 1, type: "diagram/status", payload: { status: "working" } }),
    ).toBe(true);
  });

  it("rejects anything else posted into the frame", () => {
    for (const value of [
      undefined,
      null,
      "diagram/scene",
      42,
      {},
      { ...scene, version: 2 },
      { version: 1, type: "diagram/scene" },
      { version: 1, type: "evil/command", payload: { status: "x" } },
      { ...scene, payload: { ...scene.payload, svg: 123 } },
      { ...scene, payload: { ...scene.payload, content: null } },
      { ...scene, payload: { ...scene.payload, content: { width: "10", height: 10 } } },
    ]) {
      expect(isDiagramMessage(value), JSON.stringify(value ?? null)).toBe(false);
    }
  });

  it("does not throw on a payload that would crash a naive listener", () => {
    // The bug this guards: reading message.payload.svg on a payload-less message
    // throws inside the listener, and the canvas silently stops updating.
    expect(() => isDiagramMessage({ version: 1, type: "diagram/scene" })).not.toThrow();
  });
});

describe("isWebviewReady", () => {
  it("requires the contract version, not just the type", () => {
    expect(isWebviewReady({ version: 1, type: "webview/ready" })).toBe(true);
    expect(isWebviewReady({ type: "webview/ready" })).toBe(false);
    expect(isWebviewReady({ version: 99, type: "webview/ready" })).toBe(false);
    expect(isWebviewReady(null)).toBe(false);
  });
});
