// Generated by tools/build-webview.mjs from src/webview/client/main.ts. Do not edit.
"use strict";
(() => {
  var __create = Object.create;
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __getProtoOf = Object.getPrototypeOf;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __commonJS = (cb, mod) => function __require() {
    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
    // If the importer is in node compatibility mode or this is not an ESM
    // file that has been converted to a CommonJS file using a Babel-
    // compatible transform (i.e. "__esModule" has not been set), then set
    // "default" to the CommonJS "module.exports" for node compatibility.
    isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
    mod
  ));

  // ../../packages/ui/dist/tokens.js
  var require_tokens = __commonJS({
    "../../packages/ui/dist/tokens.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.LAYOUT_TOKENS = exports.LAYOUT = exports.DESIGN_TOKENS = void 0;
      exports.renderTokenCss = renderTokenCss;
      exports.DESIGN_TOKENS = Object.freeze({
        "--mso-bg": "var(--vscode-editor-background)",
        /* Neutral area outside the drawing extent. */
        "--mso-canvas-bg": "var(--vscode-editor-background)",
        /*
         * The drawing extent itself. Modelica annotation colours are model data and
         * are never theme-remapped, and MSL icons assume a light sheet: on a dark
         * theme a themed sheet would hide the model's own dark strokes. So the sheet
         * stays a light working surface in every theme, like every other Modelica
         * tool, while the chrome around it follows the theme.
         */
        "--mso-sheet-bg": "#ffffff",
        "--mso-grid-major": "rgb(0 0 0 / 12%)",
        "--mso-grid-minor": "rgb(0 0 0 / 5%)",
        "--mso-toolbar-bg": "var(--vscode-editorWidget-background)",
        "--mso-fg": "var(--vscode-editor-foreground)",
        "--mso-border": "var(--vscode-panel-border)",
        "--mso-focus": "var(--vscode-focusBorder)",
        "--mso-hover": "var(--vscode-toolbar-hoverBackground)",
        "--mso-input-bg": "var(--vscode-input-background)",
        "--mso-input-fg": "var(--vscode-input-foreground)",
        "--mso-button-bg": "var(--vscode-button-background)",
        "--mso-button-fg": "var(--vscode-button-foreground)",
        "--mso-error": "var(--vscode-errorForeground)",
        "--mso-warning": "var(--vscode-editorWarning-foreground)",
        "--mso-description-fg": "var(--vscode-descriptionForeground)",
        "--mso-font": "var(--vscode-font-family)",
        "--mso-font-size": "var(--vscode-font-size)",
        "--mso-editor-font": "var(--vscode-editor-font-family)"
      });
      exports.LAYOUT = Object.freeze({
        /** Floating left tool rail width in CSS pixels (+-3 px tolerance). */
        toolRailWidth: 46,
        /** Reference primary sidebar width in CSS pixels (+-16 px tolerance). */
        primarySidebarWidth: 365,
        /** Reference secondary (AI) sidebar width in CSS pixels (+-24 px tolerance). */
        secondarySidebarWidth: 430,
        /** Reference capture viewport used by the visual harness. */
        referenceViewport: Object.freeze({ width: 2048, height: 1153 })
      });
      exports.LAYOUT_TOKENS = Object.freeze({
        "--mso-tool-rail-width": `${exports.LAYOUT.toolRailWidth}px`
      });
      function renderTokenCss(tokens = { ...exports.DESIGN_TOKENS, ...exports.LAYOUT_TOKENS }) {
        const body = Object.entries(tokens).map(([name, value]) => `  ${name}: ${value};`).join("\n");
        return `:root {
${body}
}`;
      }
    }
  });

  // ../../packages/ui/dist/sections.js
  var require_sections = __commonJS({
    "../../packages/ui/dist/sections.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.SIDEBAR_SECTIONS = void 0;
      exports.SIDEBAR_SECTIONS = Object.freeze([
        {
          id: "modelicaStudio.libraries",
          title: "Libraries",
          emptyState: "No Modelica libraries are loaded yet."
        },
        {
          id: "modelicaStudio.models",
          title: "Models",
          emptyState: "No Modelica models were found in this workspace."
        },
        {
          id: "modelicaStudio.results",
          title: "Results",
          emptyState: "No simulation has produced results yet."
        },
        {
          id: "modelicaStudio.figures",
          title: "Figures",
          emptyState: "No figures have been created yet."
        },
        {
          id: "modelicaStudio.documents",
          title: "Documents",
          emptyState: "No documents are attached to this workspace."
        },
        {
          id: "modelicaStudio.elements",
          title: "Elements",
          emptyState: "Open a Modelica class to inspect its elements."
        }
      ]);
    }
  });

  // ../../packages/ui/dist/render/svg.js
  var require_svg = __commonJS({
    "../../packages/ui/dist/render/svg.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.num = num;
      exports.colour = colour;
      exports.escapeXml = escapeXml;
      exports.renderShape = renderShape;
      exports.renderScene = renderScene;
      var NUMBER_PRECISION = 4;
      function num(value) {
        if (!Number.isFinite(value)) {
          return "0";
        }
        const rounded = Number(value.toFixed(NUMBER_PRECISION));
        return Object.is(rounded, -0) ? "0" : String(rounded);
      }
      function colour({ r, g, b }) {
        const channel = (value) => Math.min(255, Math.max(0, Math.round(value))).toString(16).padStart(2, "0");
        return `#${channel(r)}${channel(g)}${channel(b)}`;
      }
      function escapeXml(value) {
        return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;");
      }
      var DASH_ARRAYS = {
        Dash: "6,3",
        Dot: "1,3",
        DashDot: "6,3,1,3",
        DashDotDot: "6,3,1,3,1,3"
      };
      function paint(style, forceNoFill = false) {
        const attributes = [];
        if (style.linePattern === "None") {
          attributes.push('stroke="none"');
        } else {
          attributes.push(`stroke="${colour(style.lineColour)}"`);
          attributes.push(`stroke-width="${num(Math.max(style.lineThickness, 0.25))}"`);
          const dash = DASH_ARRAYS[style.linePattern];
          if (dash !== void 0) {
            attributes.push(`stroke-dasharray="${dash}"`);
          }
        }
        if (forceNoFill || style.fillPattern === "None") {
          attributes.push('fill="none"');
        } else if (style.fillPattern === "Solid") {
          attributes.push(`fill="${colour(style.fillColour)}"`);
        } else {
          attributes.push(`fill="${colour(style.fillColour)}"`);
          attributes.push(`data-fill-pattern="${style.fillPattern}"`);
        }
        return attributes.join(" ");
      }
      function transform(style) {
        const parts = [];
        if (style.origin.x !== 0 || style.origin.y !== 0) {
          parts.push(`translate(${num(style.origin.x)},${num(style.origin.y)})`);
        }
        if (style.rotation !== 0) {
          parts.push(`rotate(${num(-style.rotation)})`);
        }
        return parts.length === 0 ? "" : ` transform="${parts.join(" ")}"`;
      }
      function normalise(extent2) {
        const x = Math.min(extent2.min.x, extent2.max.x);
        const y = Math.min(extent2.min.y, extent2.max.y);
        return {
          x,
          y,
          width: Math.abs(extent2.max.x - extent2.min.x),
          height: Math.abs(extent2.max.y - extent2.min.y)
        };
      }
      function polyline(points) {
        return points.map((point) => `${num(point.x)},${num(point.y)}`).join(" ");
      }
      function bezierPath(points) {
        if (points.length < 3) {
          return `M ${points.map((p) => `${num(p.x)} ${num(p.y)}`).join(" L ")}`;
        }
        const segments = [`M ${num(points[0].x)} ${num(points[0].y)}`];
        for (let index = 0; index < points.length - 1; index += 1) {
          const p0 = points[Math.max(index - 1, 0)];
          const p1 = points[index];
          const p2 = points[index + 1];
          const p3 = points[Math.min(index + 2, points.length - 1)];
          const c1 = { x: p1.x + (p2.x - p0.x) / 6, y: p1.y + (p2.y - p0.y) / 6 };
          const c2 = { x: p2.x - (p3.x - p1.x) / 6, y: p2.y - (p3.y - p1.y) / 6 };
          segments.push(`C ${num(c1.x)} ${num(c1.y)}, ${num(c2.x)} ${num(c2.y)}, ${num(p2.x)} ${num(p2.y)}`);
        }
        return segments.join(" ");
      }
      var ANCHORS = { Left: "start", Center: "middle", Right: "end" };
      function renderShape(shape) {
        if (!shape.style.visible) {
          return "";
        }
        const tf = transform(shape.style);
        switch (shape.kind) {
          case "line": {
            if (shape.points.length < 2) {
              return "";
            }
            const stroke = paint(shape.style, true);
            const marker = shape.arrow[1] === "None" ? "" : ' marker-end="url(#arrow)"';
            const markerStart = shape.arrow[0] === "None" ? "" : ' marker-start="url(#arrow)"';
            if (shape.smooth === "Bezier") {
              return `<path${tf} d="${bezierPath(shape.points)}" ${stroke}${markerStart}${marker}/>`;
            }
            return `<polyline${tf} points="${polyline(shape.points)}" ${stroke}${markerStart}${marker}/>`;
          }
          case "rectangle": {
            const box = normalise(shape.extent);
            const radius = shape.radius > 0 ? ` rx="${num(shape.radius)}" ry="${num(shape.radius)}"` : "";
            return `<rect${tf} x="${num(box.x)}" y="${num(box.y)}" width="${num(box.width)}" height="${num(box.height)}"${radius} ${paint(shape.style)}/>`;
          }
          case "ellipse": {
            const box = normalise(shape.extent);
            const rx = box.width / 2;
            const ry = box.height / 2;
            const cx = box.x + rx;
            const cy = box.y + ry;
            const full = Math.abs(shape.endAngle - shape.startAngle) >= 360;
            if (full) {
              return `<ellipse${tf} cx="${num(cx)}" cy="${num(cy)}" rx="${num(rx)}" ry="${num(ry)}" ${paint(shape.style)}/>`;
            }
            const toRadians = (degrees) => degrees * Math.PI / 180;
            const start = {
              x: cx + rx * Math.cos(toRadians(shape.startAngle)),
              y: cy + ry * Math.sin(toRadians(shape.startAngle))
            };
            const end = {
              x: cx + rx * Math.cos(toRadians(shape.endAngle)),
              y: cy + ry * Math.sin(toRadians(shape.endAngle))
            };
            const largeArc = Math.abs(shape.endAngle - shape.startAngle) > 180 ? 1 : 0;
            const sweep = shape.endAngle > shape.startAngle ? 1 : 0;
            const path = `M ${num(start.x)} ${num(start.y)} A ${num(rx)} ${num(ry)} 0 ${largeArc} ${sweep} ${num(end.x)} ${num(end.y)}`;
            return `<path${tf} d="${path}" ${paint(shape.style)}/>`;
          }
          case "polygon": {
            if (shape.points.length < 3) {
              return "";
            }
            if (shape.smooth === "Bezier") {
              return `<path${tf} d="${bezierPath(shape.points)} Z" ${paint(shape.style)}/>`;
            }
            return `<polygon${tf} points="${polyline(shape.points)}" ${paint(shape.style)}/>`;
          }
          case "text": {
            const box = normalise(shape.extent);
            if (shape.text === "") {
              return "";
            }
            const size2 = shape.fontSize > 0 ? shape.fontSize : Math.max(box.height * 0.8, 1);
            const anchor = ANCHORS[shape.horizontalAlignment] ?? "middle";
            const x = shape.horizontalAlignment === "Left" ? box.x : shape.horizontalAlignment === "Right" ? box.x + box.width : box.x + box.width / 2;
            const y = box.y + box.height / 2;
            const font = shape.fontName === "" ? "" : ` font-family="${escapeXml(shape.fontName)}"`;
            const weight = shape.textStyle.includes("Bold") ? ' font-weight="bold"' : "";
            const italic = shape.textStyle.includes("Italic") ? ' font-style="italic"' : "";
            const underline = shape.textStyle.includes("UnderLine") ? ' text-decoration="underline"' : "";
            return `<text${tf} x="${num(x)}" y="${num(y)}" fill="${colour(shape.textColour)}" font-size="${num(size2)}"${font}${weight}${italic}${underline} text-anchor="${anchor}" dominant-baseline="central" transform-origin="${num(x)} ${num(y)}" style="transform: scaleY(-1)">${escapeXml(shape.text)}</text>`;
          }
          case "bitmap": {
            const box = normalise(shape.extent);
            const href = shape.imageSource !== void 0 && shape.imageSource !== "" ? `data:image;base64,${shape.imageSource}` : shape.fileName ?? "";
            if (href === "") {
              return "";
            }
            return `<image${tf} x="${num(box.x)}" y="${num(box.y)}" width="${num(box.width)}" height="${num(box.height)}" href="${escapeXml(href)}" transform-origin="${num(box.x + box.width / 2)} ${num(box.y + box.height / 2)}" style="transform: scaleY(-1)"/>`;
          }
        }
      }
      function renderScene(shapes, coordinateSystem, options = {}) {
        const padding = options.padding ?? 0;
        const system = normalise(coordinateSystem.extent);
        const viewBox = {
          min: { x: system.x - padding, y: system.y - padding },
          max: { x: system.x + system.width + padding, y: system.y + system.height + padding }
        };
        const boxWidth = Math.max(viewBox.max.x - viewBox.min.x, 1);
        const boxHeight = Math.max(viewBox.max.y - viewBox.min.y, 1);
        const width = options.width ?? boxWidth;
        const height = width * boxHeight / boxWidth;
        const aspect = coordinateSystem.preserveAspectRatio ? "xMidYMid meet" : "none";
        const name = options.name === void 0 ? "" : ` data-name="${escapeXml(options.name)}"`;
        const body = shapes.map((shape) => renderShape(shape)).filter((markup) => markup !== "").join("\n    ");
        return {
          svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${num(viewBox.min.x)} ${num(-viewBox.max.y)} ${num(boxWidth)} ${num(boxHeight)}" width="${num(width)}" height="${num(height)}" preserveAspectRatio="${aspect}"${name}>
  <g transform="scale(1,-1)">
    ${body}
  </g>
</svg>`,
          width,
          height,
          viewBox
        };
      }
    }
  });

  // ../../packages/ui/dist/render/scene.js
  var require_scene = __commonJS({
    "../../packages/ui/dist/render/scene.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.componentTransform = componentTransform;
      exports.renderSceneGraph = renderSceneGraph;
      var svg_js_1 = require_svg();
      function span(extent2) {
        const x = Math.min(extent2.min.x, extent2.max.x);
        const y = Math.min(extent2.min.y, extent2.max.y);
        return {
          x,
          y,
          width: Math.abs(extent2.max.x - extent2.min.x),
          height: Math.abs(extent2.max.y - extent2.min.y)
        };
      }
      function componentTransform(component) {
        const source = span(component.iconCoordinateSystem.extent);
        const target = {
          min: {
            x: component.origin.x + component.extent.min.x,
            y: component.origin.y + component.extent.min.y
          },
          max: {
            x: component.origin.x + component.extent.max.x,
            y: component.origin.y + component.extent.max.y
          }
        };
        const box = span(target);
        const scaleX = source.width === 0 ? 1 : box.width / source.width;
        const scaleY = source.height === 0 ? 1 : box.height / source.height;
        const signX = component.flipHorizontal ? -1 : 1;
        const signY = component.flipVertical ? -1 : 1;
        const centre = { x: box.x + box.width / 2, y: box.y + box.height / 2 };
        const sourceCentre = { x: source.x + source.width / 2, y: source.y + source.height / 2 };
        const parts = [`translate(${(0, svg_js_1.num)(centre.x)},${(0, svg_js_1.num)(centre.y)})`];
        if (component.rotation !== 0) {
          parts.push(`rotate(${(0, svg_js_1.num)(-component.rotation)})`);
        }
        if (scaleX * signX !== 1 || scaleY * signY !== 1) {
          parts.push(`scale(${(0, svg_js_1.num)(scaleX * signX)},${(0, svg_js_1.num)(scaleY * signY)})`);
        }
        if (sourceCentre.x !== 0 || sourceCentre.y !== 0) {
          parts.push(`translate(${(0, svg_js_1.num)(-sourceCentre.x)},${(0, svg_js_1.num)(-sourceCentre.y)})`);
        }
        return parts.join(" ");
      }
      function renderComponent(component) {
        if (!component.visible) {
          return "";
        }
        const body = component.icon.map((shape) => (0, svg_js_1.renderShape)(shape)).filter((markup) => markup !== "").join("\n      ");
        if (body === "") {
          return "";
        }
        return `<g class="mso-component" data-instance="${(0, svg_js_1.escapeXml)(component.instanceName)}" data-class="${(0, svg_js_1.escapeXml)(component.className)}" transform="${componentTransform(component)}">
      ${body}
    </g>`;
      }
      function renderSceneGraph(scene, options = {}) {
        const padding = options.padding ?? 0;
        const system = span(scene.coordinateSystem.extent);
        const viewBox = {
          min: { x: system.x - padding, y: system.y - padding },
          max: { x: system.x + system.width + padding, y: system.y + system.height + padding }
        };
        const boxWidth = Math.max(viewBox.max.x - viewBox.min.x, 1);
        const boxHeight = Math.max(viewBox.max.y - viewBox.min.y, 1);
        const width = options.width ?? boxWidth;
        const height = width * boxHeight / boxWidth;
        const layers = [];
        const own = scene.shapes.map((shape) => (0, svg_js_1.renderShape)(shape)).filter((markup) => markup !== "").join("\n      ");
        if (own !== "") {
          layers.push(`<g class="mso-layer-graphics">
      ${own}
    </g>`);
        }
        const components = scene.components.map((component) => renderComponent(component)).filter((markup) => markup !== "");
        if (components.length > 0) {
          layers.push(`<g class="mso-layer-components">
    ${components.join("\n    ")}
    </g>`);
        }
        const connections = scene.connections.map((connection) => {
          const markup = (0, svg_js_1.renderShape)(connection.shape);
          if (markup === "") {
            return "";
          }
          return `<g class="mso-connection" data-from="${(0, svg_js_1.escapeXml)(connection.from)}" data-to="${(0, svg_js_1.escapeXml)(connection.to)}">${markup}</g>`;
        }).filter((markup) => markup !== "");
        if (connections.length > 0) {
          layers.push(`<g class="mso-layer-connections">
    ${connections.join("\n    ")}
    </g>`);
        }
        const aspect = scene.coordinateSystem.preserveAspectRatio ? "xMidYMid meet" : "none";
        return {
          svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${(0, svg_js_1.num)(viewBox.min.x)} ${(0, svg_js_1.num)(-viewBox.max.y)} ${(0, svg_js_1.num)(boxWidth)} ${(0, svg_js_1.num)(boxHeight)}" width="${(0, svg_js_1.num)(width)}" height="${(0, svg_js_1.num)(height)}" preserveAspectRatio="${aspect}" data-class="${(0, svg_js_1.escapeXml)(scene.className)}" data-view="${scene.view}">
  <g transform="scale(1,-1)">
    ${layers.join("\n    ")}
  </g>
</svg>`,
          width,
          height,
          viewBox
        };
      }
    }
  });

  // ../../packages/ui/dist/view/viewport.js
  var require_viewport = __commonJS({
    "../../packages/ui/dist/view/viewport.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.GRID_MINOR_MIN_PX = exports.GRID_MAJOR_STEP = exports.GRID_MINOR_STEP = exports.IDENTITY_VIEWPORT = exports.ZOOM_STEP = exports.FIT_PADDING = exports.MAX_SCALE = exports.MIN_SCALE = void 0;
      exports.clampScale = clampScale;
      exports.fitViewport = fitViewport2;
      exports.zoomAt = zoomAt2;
      exports.zoomBy = zoomBy2;
      exports.panBy = panBy2;
      exports.toCssTransform = toCssTransform2;
      exports.extentGeometry = extentGeometry2;
      exports.formatZoom = formatZoom2;
      exports.MIN_SCALE = 0.05;
      exports.MAX_SCALE = 40;
      exports.FIT_PADDING = 0.06;
      exports.ZOOM_STEP = 1.2;
      exports.IDENTITY_VIEWPORT = { scale: 1, x: 0, y: 0 };
      function clampScale(scale) {
        if (Number.isNaN(scale) || scale <= 0) {
          return 1;
        }
        return Math.min(exports.MAX_SCALE, Math.max(exports.MIN_SCALE, scale));
      }
      function fitViewport2(content2, size2, padding = exports.FIT_PADDING) {
        if (!Number.isFinite(content2.width) || !Number.isFinite(content2.height) || content2.width <= 0 || content2.height <= 0 || size2.width <= 0 || size2.height <= 0) {
          return exports.IDENTITY_VIEWPORT;
        }
        const usableWidth = size2.width * (1 - 2 * padding);
        const usableHeight = size2.height * (1 - 2 * padding);
        const scale = clampScale(Math.min(usableWidth / content2.width, usableHeight / content2.height));
        return {
          scale,
          x: (size2.width - content2.width * scale) / 2,
          y: (size2.height - content2.height * scale) / 2
        };
      }
      function zoomAt2(view2, factor, pointer) {
        const target = clampScale(view2.scale * factor);
        if (target === view2.scale) {
          return view2;
        }
        const ratio = target / view2.scale;
        return {
          scale: target,
          x: pointer.x - (pointer.x - view2.x) * ratio,
          y: pointer.y - (pointer.y - view2.y) * ratio
        };
      }
      function zoomBy2(view2, factor, size2) {
        return zoomAt2(view2, factor, { x: size2.width / 2, y: size2.height / 2 });
      }
      function panBy2(view2, dx, dy) {
        if (!Number.isFinite(dx) || !Number.isFinite(dy)) {
          return view2;
        }
        return { scale: view2.scale, x: view2.x + dx, y: view2.y + dy };
      }
      function toCssTransform2(view2) {
        return `translate(${round(view2.x)}px, ${round(view2.y)}px) scale(${round(view2.scale)})`;
      }
      exports.GRID_MINOR_STEP = 10;
      exports.GRID_MAJOR_STEP = 100;
      exports.GRID_MINOR_MIN_PX = 4;
      function extentGeometry2(view2, content2) {
        const minorPx = exports.GRID_MINOR_STEP * view2.scale;
        return {
          left: view2.x,
          top: view2.y,
          width: content2.width * view2.scale,
          height: content2.height * view2.scale,
          minorPx,
          majorPx: exports.GRID_MAJOR_STEP * view2.scale,
          minorVisible: minorPx >= exports.GRID_MINOR_MIN_PX,
          visible: content2.width > 0 && content2.height > 0
        };
      }
      function formatZoom2(view2) {
        return `${Math.round(view2.scale * 100)}%`;
      }
      function round(value) {
        return Math.round(value * 1e4) / 1e4;
      }
    }
  });

  // ../../packages/ui/dist/view/editMath.js
  var require_editMath = __commonJS({
    "../../packages/ui/dist/view/editMath.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.screenDeltaToModel = screenDeltaToModel2;
      function screenDeltaToModel2(dxScreen, dyScreen, pxPerUnit, scale) {
        if (!Number.isFinite(pxPerUnit) || pxPerUnit <= 0 || !Number.isFinite(scale) || scale <= 0) {
          return { dx: 0, dy: 0 };
        }
        const factor = pxPerUnit * scale;
        return {
          dx: dxScreen / factor,
          // Screen y is inverted relative to Modelica y.
          dy: -dyScreen / factor
        };
      }
    }
  });

  // ../../packages/ui/dist/index.js
  var require_dist = __commonJS({
    "../../packages/ui/dist/index.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.screenDeltaToModel = exports.zoomBy = exports.zoomAt = exports.toCssTransform = exports.panBy = exports.formatZoom = exports.fitViewport = exports.extentGeometry = exports.clampScale = exports.ZOOM_STEP = exports.MIN_SCALE = exports.MAX_SCALE = exports.IDENTITY_VIEWPORT = exports.GRID_MINOR_STEP = exports.GRID_MINOR_MIN_PX = exports.GRID_MAJOR_STEP = exports.FIT_PADDING = exports.renderSceneGraph = exports.componentTransform = exports.renderShape = exports.renderScene = exports.num = exports.escapeXml = exports.colour = exports.SIDEBAR_SECTIONS = exports.renderTokenCss = exports.LAYOUT = exports.DESIGN_TOKENS = void 0;
      var tokens_js_1 = require_tokens();
      Object.defineProperty(exports, "DESIGN_TOKENS", { enumerable: true, get: function() {
        return tokens_js_1.DESIGN_TOKENS;
      } });
      Object.defineProperty(exports, "LAYOUT", { enumerable: true, get: function() {
        return tokens_js_1.LAYOUT;
      } });
      Object.defineProperty(exports, "renderTokenCss", { enumerable: true, get: function() {
        return tokens_js_1.renderTokenCss;
      } });
      var sections_js_1 = require_sections();
      Object.defineProperty(exports, "SIDEBAR_SECTIONS", { enumerable: true, get: function() {
        return sections_js_1.SIDEBAR_SECTIONS;
      } });
      var svg_js_1 = require_svg();
      Object.defineProperty(exports, "colour", { enumerable: true, get: function() {
        return svg_js_1.colour;
      } });
      Object.defineProperty(exports, "escapeXml", { enumerable: true, get: function() {
        return svg_js_1.escapeXml;
      } });
      Object.defineProperty(exports, "num", { enumerable: true, get: function() {
        return svg_js_1.num;
      } });
      Object.defineProperty(exports, "renderScene", { enumerable: true, get: function() {
        return svg_js_1.renderScene;
      } });
      Object.defineProperty(exports, "renderShape", { enumerable: true, get: function() {
        return svg_js_1.renderShape;
      } });
      var scene_js_1 = require_scene();
      Object.defineProperty(exports, "componentTransform", { enumerable: true, get: function() {
        return scene_js_1.componentTransform;
      } });
      Object.defineProperty(exports, "renderSceneGraph", { enumerable: true, get: function() {
        return scene_js_1.renderSceneGraph;
      } });
      var viewport_js_1 = require_viewport();
      Object.defineProperty(exports, "FIT_PADDING", { enumerable: true, get: function() {
        return viewport_js_1.FIT_PADDING;
      } });
      Object.defineProperty(exports, "GRID_MAJOR_STEP", { enumerable: true, get: function() {
        return viewport_js_1.GRID_MAJOR_STEP;
      } });
      Object.defineProperty(exports, "GRID_MINOR_MIN_PX", { enumerable: true, get: function() {
        return viewport_js_1.GRID_MINOR_MIN_PX;
      } });
      Object.defineProperty(exports, "GRID_MINOR_STEP", { enumerable: true, get: function() {
        return viewport_js_1.GRID_MINOR_STEP;
      } });
      Object.defineProperty(exports, "IDENTITY_VIEWPORT", { enumerable: true, get: function() {
        return viewport_js_1.IDENTITY_VIEWPORT;
      } });
      Object.defineProperty(exports, "MAX_SCALE", { enumerable: true, get: function() {
        return viewport_js_1.MAX_SCALE;
      } });
      Object.defineProperty(exports, "MIN_SCALE", { enumerable: true, get: function() {
        return viewport_js_1.MIN_SCALE;
      } });
      Object.defineProperty(exports, "ZOOM_STEP", { enumerable: true, get: function() {
        return viewport_js_1.ZOOM_STEP;
      } });
      Object.defineProperty(exports, "clampScale", { enumerable: true, get: function() {
        return viewport_js_1.clampScale;
      } });
      Object.defineProperty(exports, "extentGeometry", { enumerable: true, get: function() {
        return viewport_js_1.extentGeometry;
      } });
      Object.defineProperty(exports, "fitViewport", { enumerable: true, get: function() {
        return viewport_js_1.fitViewport;
      } });
      Object.defineProperty(exports, "formatZoom", { enumerable: true, get: function() {
        return viewport_js_1.formatZoom;
      } });
      Object.defineProperty(exports, "panBy", { enumerable: true, get: function() {
        return viewport_js_1.panBy;
      } });
      Object.defineProperty(exports, "toCssTransform", { enumerable: true, get: function() {
        return viewport_js_1.toCssTransform;
      } });
      Object.defineProperty(exports, "zoomAt", { enumerable: true, get: function() {
        return viewport_js_1.zoomAt;
      } });
      Object.defineProperty(exports, "zoomBy", { enumerable: true, get: function() {
        return viewport_js_1.zoomBy;
      } });
      var editMath_js_1 = require_editMath();
      Object.defineProperty(exports, "screenDeltaToModel", { enumerable: true, get: function() {
        return editMath_js_1.screenDeltaToModel;
      } });
    }
  });

  // src/webview/client/main.ts
  var import_ui = __toESM(require_dist());

  // src/webview/protocol.ts
  var PROTOCOL_VERSION = 1;
  function isDiagramMessage(message) {
    if (!isVersionedMessage(message)) {
      return false;
    }
    const { type, payload } = message;
    if (typeof payload !== "object" || payload === null) {
      return false;
    }
    const fields = payload;
    if (typeof fields["status"] !== "string") {
      return false;
    }
    if (type === "diagram/status") {
      return true;
    }
    if (type !== "diagram/scene") {
      return false;
    }
    const content2 = fields["content"];
    if (typeof content2 !== "object" || content2 === null) {
      return false;
    }
    const size2 = content2;
    const viewBox = fields["viewBox"];
    if (typeof viewBox !== "object" || viewBox === null) {
      return false;
    }
    const box = viewBox;
    return typeof fields["svg"] === "string" && typeof fields["label"] === "string" && typeof fields["revision"] === "number" && typeof size2["width"] === "number" && typeof size2["height"] === "number" && typeof box["width"] === "number" && typeof box["height"] === "number";
  }
  function isVersionedMessage(message) {
    return typeof message === "object" && message !== null && message.version === PROTOCOL_VERSION;
  }
  function isPlotDataMessage(message) {
    if (!isVersionedMessage(message)) {
      return false;
    }
    const { type, payload } = message;
    if (type !== "plot/data" || typeof payload !== "object" || payload === null) {
      return false;
    }
    const fields = payload;
    if (typeof fields["file"] !== "string" || !Array.isArray(fields["series"])) {
      return false;
    }
    return fields["series"].every(
      (entry) => typeof entry === "object" && entry !== null && typeof entry["name"] === "string" && Array.isArray(entry["values"])
    );
  }
  function isEditResultMessage(message) {
    if (typeof message !== "object" || message === null) {
      return false;
    }
    const { version, type, payload } = message;
    if (version !== PROTOCOL_VERSION || type !== "edit/result" || typeof payload !== "object" || payload === null) {
      return false;
    }
    const fields = payload;
    return typeof fields["ok"] === "boolean" && typeof fields["revision"] === "number";
  }

  // src/webview/client/sanitise.ts
  var FORBIDDEN_ELEMENTS = /* @__PURE__ */ new Set(["script", "foreignobject", "iframe", "object", "embed", "a"]);
  var URL_ATTRIBUTES = /* @__PURE__ */ new Set(["href", "xlink:href", "src"]);
  function sanitiseSvg(root) {
    for (const child of Array.from(root.children)) {
      if (FORBIDDEN_ELEMENTS.has(child.nodeName.toLowerCase())) {
        child.remove();
        continue;
      }
      sanitiseSvg(child);
    }
    for (const attribute of Array.from(root.attributes)) {
      const name = attribute.name.toLowerCase();
      if (name.startsWith("on")) {
        root.removeAttribute(attribute.name);
        continue;
      }
      if (URL_ATTRIBUTES.has(name) && !isSafeUrl(attribute.value)) {
        root.removeAttribute(attribute.name);
      }
    }
  }
  function isSafeUrl(value) {
    const url = value.replace(/[\u0000-\u0020]/g, "").trim().toLowerCase();
    return url.startsWith("#") || url.startsWith("data:image/");
  }

  // src/webview/client/main.ts
  var CONTRACT_VERSION = 1;
  var DRAG_THRESHOLD_PX = 3;
  var vscode = acquireVsCodeApi();
  var sheet = document.getElementById("mso-sheet");
  var stage = document.getElementById("mso-stage");
  var extent = document.getElementById("mso-extent");
  var status = document.getElementById("mso-status");
  var zoomReadout = document.getElementById("mso-zoom");
  if (sheet === null || stage === null || extent === null || status === null || zoomReadout === null) {
    throw new Error("diagram shell is missing its canvas elements");
  }
  var content = { width: 0, height: 0 };
  var viewBoxWidth = 1;
  var view = import_ui.IDENTITY_VIEWPORT;
  var following = true;
  var currentRevision = 0;
  var selected;
  var connectFrom;
  function size() {
    const box = sheet.getBoundingClientRect();
    return { width: box.width, height: box.height };
  }
  function apply() {
    stage.style.transform = (0, import_ui.toCssTransform)(view);
    zoomReadout.textContent = (0, import_ui.formatZoom)(view);
    const geometry = (0, import_ui.extentGeometry)(view, content);
    const style = extent.style;
    style.left = `${geometry.left}px`;
    style.top = `${geometry.top}px`;
    style.width = `${geometry.width}px`;
    style.height = `${geometry.height}px`;
    style.setProperty("--mso-grid-minor-size", `${geometry.minorPx}px`);
    style.setProperty("--mso-grid-major-size", `${geometry.majorPx}px`);
    style.setProperty("--mso-grid-minor", geometry.minorVisible ? "" : "transparent");
    extent.hidden = !geometry.visible;
  }
  function setView(next, userDriven) {
    view = next;
    if (userDriven) {
      following = false;
    }
    apply();
  }
  function fit(userDriven) {
    view = (0, import_ui.fitViewport)(content, size());
    if (userDriven) {
      following = true;
    }
    apply();
  }
  function showScene(svg, pixelSize, label, viewBox) {
    const parsed = new DOMParser().parseFromString(svg, "image/svg+xml");
    const root = parsed.documentElement;
    if (root.nodeName !== "svg" || parsed.getElementsByTagName("parsererror").length > 0) {
      status.textContent = "The diagram could not be rendered.";
      return;
    }
    sanitiseSvg(root);
    stage.replaceChildren(document.importNode(root, true));
    content = inkSize(pixelSize);
    viewBoxWidth = viewBox.width > 0 ? viewBox.width : 1;
    sheet.setAttribute("aria-label", label);
    clearSelection();
    for (const button of Array.from(
      document.querySelectorAll("[data-view-tool]")
    )) {
      button.disabled = false;
    }
    fit(true);
  }
  function select(instance) {
    if (connectFrom !== void 0 && connectFrom !== instance) {
      vscode.postMessage({
        version: CONTRACT_VERSION,
        type: "document/edit",
        revision: currentRevision,
        payload: [{ kind: "connect", from: connectFrom, to: instance }]
      });
      connectFrom = void 0;
      sheet.removeAttribute("data-wiring");
      return;
    }
    clearSelection();
    selected = instance;
    const node = stage.querySelector(`[data-instance="${instance}"]`);
    if (node !== null) {
      node.classList.add("is-selected");
    }
    sheet.setAttribute(
      "aria-label",
      `Selected ${instance}. Use arrow keys to move, Escape to deselect.`
    );
  }
  function beginWiring() {
    connectFrom = void 0;
    clearSelection();
    sheet.setAttribute("data-wiring", "true");
    sheet.setAttribute("aria-label", "Wiring: select the first component to connect.");
  }
  function clearSelection() {
    if (selected !== void 0) {
      const node = stage.querySelector(`[data-instance="${selected}"]`);
      node?.classList.remove("is-selected");
    }
    selected = void 0;
  }
  function toModelDelta(dxScreen, dyScreen) {
    const pxPerUnit = viewBoxWidth > 0 ? content.width / viewBoxWidth : 1;
    return (0, import_ui.screenDeltaToModel)(dxScreen, dyScreen, pxPerUnit, view.scale);
  }
  function sendMove(instance, dxScreen, dyScreen) {
    const { dx, dy } = toModelDelta(dxScreen, dyScreen);
    if (dx === 0 && dy === 0) {
      return;
    }
    vscode.postMessage({
      version: CONTRACT_VERSION,
      type: "document/edit",
      revision: currentRevision,
      payload: [{ kind: "moveComponent", instanceName: instance, dx, dy }]
    });
  }
  function inkSize(declared) {
    const svg = stage.firstElementChild;
    if (svg === null || typeof svg.getBBox !== "function") {
      return declared;
    }
    const viewBox = svg.viewBox.baseVal;
    if (viewBox.width <= 0 || viewBox.height <= 0) {
      return declared;
    }
    let box;
    try {
      box = svg.getBBox();
    } catch {
      return declared;
    }
    if (box.width <= 0 || box.height <= 0) {
      return declared;
    }
    const minX = Math.min(viewBox.x, box.x);
    const minY = Math.min(viewBox.y, box.y);
    const spanX = Math.max(viewBox.x + viewBox.width, box.x + box.width) - minX;
    const spanY = Math.max(viewBox.y + viewBox.height, box.y + box.height) - minY;
    if (spanX <= viewBox.width && spanY <= viewBox.height) {
      return declared;
    }
    const pxPerUnitX = declared.width / viewBox.width;
    const pxPerUnitY = declared.height / viewBox.height;
    svg.style.transform = `translate(${(viewBox.x - minX) * pxPerUnitX}px, ${(viewBox.y - minY) * pxPerUnitY}px)`;
    return { width: spanX * pxPerUnitX, height: spanY * pxPerUnitY };
  }
  var drag;
  sheet.addEventListener("pointerdown", (event) => {
    if (event.button !== 0) {
      return;
    }
    const target = event.target;
    const hit = target?.closest("[data-instance]");
    drag = {
      pointerId: event.pointerId,
      lastX: event.clientX,
      lastY: event.clientY,
      totalX: 0,
      totalY: 0,
      instance: hit?.getAttribute("data-instance") ?? void 0,
      moving: false
    };
    if (drag.instance !== void 0) {
      const instance = drag.instance;
      if (sheet.hasAttribute("data-wiring")) {
        if (connectFrom === void 0) {
          connectFrom = instance;
          sheet.setAttribute("aria-label", `Wiring from ${instance}: select the second component.`);
        } else {
          select(instance);
        }
      } else {
        select(instance);
      }
      sheet.setPointerCapture(event.pointerId);
    } else {
      clearSelection();
      sheet.setPointerCapture(event.pointerId);
      sheet.classList.add("is-panning");
    }
  });
  sheet.addEventListener("pointermove", (event) => {
    if (drag === void 0 || drag.pointerId !== event.pointerId) {
      return;
    }
    const dx = event.clientX - drag.lastX;
    const dy = event.clientY - drag.lastY;
    drag.lastX = event.clientX;
    drag.lastY = event.clientY;
    drag.totalX += dx;
    drag.totalY += dy;
    if (drag.instance !== void 0) {
      if (!drag.moving && Math.hypot(drag.totalX, drag.totalY) < DRAG_THRESHOLD_PX) {
        return;
      }
      drag.moving = true;
      sendMove(drag.instance, dx, dy);
      return;
    }
    setView((0, import_ui.panBy)(view, dx, dy), true);
  });
  var endDrag = (event) => {
    if (drag?.pointerId !== event.pointerId) {
      return;
    }
    drag = void 0;
    sheet.releasePointerCapture(event.pointerId);
    sheet.classList.remove("is-panning");
  };
  sheet.addEventListener("pointerup", endDrag);
  sheet.addEventListener("pointercancel", endDrag);
  sheet.addEventListener(
    "wheel",
    (event) => {
      const box = sheet.getBoundingClientRect();
      if (event.ctrlKey || event.metaKey) {
        event.preventDefault();
        const factor = Math.pow(import_ui.ZOOM_STEP, -Math.sign(event.deltaY));
        setView(
          (0, import_ui.zoomAt)(view, factor, { x: event.clientX - box.left, y: event.clientY - box.top }),
          true
        );
        return;
      }
      event.preventDefault();
      const horizontal = event.shiftKey ? event.deltaY : event.deltaX;
      const vertical = event.shiftKey ? 0 : event.deltaY;
      setView((0, import_ui.panBy)(view, -horizontal, -vertical), true);
    },
    { passive: false }
  );
  for (const button of Array.from(document.querySelectorAll("[data-view-tool]"))) {
    button.addEventListener("click", () => {
      switch (button.dataset["viewTool"]) {
        case "zoom-in":
          setView((0, import_ui.zoomBy)(view, import_ui.ZOOM_STEP, size()), true);
          break;
        case "zoom-out":
          setView((0, import_ui.zoomBy)(view, 1 / import_ui.ZOOM_STEP, size()), true);
          break;
        case "reset":
          setView(import_ui.IDENTITY_VIEWPORT, true);
          break;
        case "wire":
          beginWiring();
          break;
        default:
          fit(true);
      }
    });
  }
  sheet.addEventListener("keydown", (event) => {
    const step = event.shiftKey ? 100 : 20;
    switch (event.key) {
      case "ArrowLeft":
        setView((0, import_ui.panBy)(view, step, 0), true);
        break;
      case "ArrowRight":
        setView((0, import_ui.panBy)(view, -step, 0), true);
        break;
      case "ArrowUp":
        setView((0, import_ui.panBy)(view, 0, step), true);
        break;
      case "ArrowDown":
        setView((0, import_ui.panBy)(view, 0, -step), true);
        break;
      case "+":
      case "=":
        setView((0, import_ui.zoomBy)(view, import_ui.ZOOM_STEP, size()), true);
        break;
      case "-":
        setView((0, import_ui.zoomBy)(view, 1 / import_ui.ZOOM_STEP, size()), true);
        break;
      case "0":
        fit(true);
        break;
      case "Escape":
        clearSelection();
        break;
      case "z":
      case "Z":
        if (event.ctrlKey || event.metaKey) {
          if (event.shiftKey) {
            vscode.postMessage({ version: CONTRACT_VERSION, type: "document/redo" });
          } else {
            vscode.postMessage({ version: CONTRACT_VERSION, type: "document/undo" });
          }
          event.preventDefault();
        }
        return;
      case "y":
      case "Y":
        if (event.ctrlKey || event.metaKey) {
          vscode.postMessage({ version: CONTRACT_VERSION, type: "document/redo" });
          event.preventDefault();
        }
        return;
      case "Delete":
      case "Backspace":
        if (selected !== void 0) {
          vscode.postMessage({
            version: CONTRACT_VERSION,
            type: "document/edit",
            revision: currentRevision,
            payload: [{ kind: "removeComponent", instanceName: selected }]
          });
          event.preventDefault();
        }
        return;
      default:
        return;
    }
    event.preventDefault();
  });
  sheet.addEventListener("keydown", (event) => {
    if (selected === void 0) {
      return;
    }
    const step = event.shiftKey ? 20 : 5;
    let dx = 0;
    let dy = 0;
    switch (event.key) {
      case "ArrowLeft":
        dx = -step;
        break;
      case "ArrowRight":
        dx = step;
        break;
      case "ArrowUp":
        dy = step;
        break;
      case "ArrowDown":
        dy = -step;
        break;
      default:
        return;
    }
    vscode.postMessage({
      version: CONTRACT_VERSION,
      type: "document/edit",
      revision: currentRevision,
      payload: [{ kind: "moveComponent", instanceName: selected, dx, dy }]
    });
    event.preventDefault();
  });
  new ResizeObserver(() => {
    if (following) {
      fit(false);
    }
  }).observe(sheet);
  window.addEventListener("message", (event) => {
    const message = event.data;
    if (isEditResultMessage(message)) {
      currentRevision = message.payload.revision;
      if (!message.payload.ok) {
        status.textContent = `Edit refused: ${message.payload.reason}`;
      }
      return;
    }
    if (!isDiagramMessage(message)) {
      return;
    }
    switch (message.type) {
      case "diagram/scene":
        showScene(
          message.payload.svg,
          message.payload.content,
          message.payload.label,
          message.payload.viewBox
        );
        currentRevision = message.payload.revision;
        status.textContent = message.payload.status;
        break;
      case "diagram/status":
        status.textContent = message.payload.status;
        break;
      default:
        break;
    }
  });
  window.addEventListener("message", (event) => {
    const message = event.data;
    if (!isPlotDataMessage(message)) {
      return;
    }
    renderPlot(message.payload);
  });
  function renderPlot(payload) {
    if (payload.series.length === 0) {
      status.textContent = `No data in ${payload.file}.`;
      return;
    }
    const width = 640;
    const height = 360;
    const pad = { left: 56, right: 16, top: 16, bottom: 36 };
    const plotW = width - pad.left - pad.right;
    const plotH = height - pad.top - pad.bottom;
    const x = payload.series[0].values;
    const xMin = Math.min(...x.filter((v) => Number.isFinite(v)));
    const xMax = Math.max(...x.filter((v) => Number.isFinite(v)));
    const xSpan = xMax - xMin || 1;
    let yMin = Infinity;
    let yMax = -Infinity;
    for (const series of payload.series) {
      for (const value of series.values) {
        if (Number.isFinite(value)) {
          yMin = Math.min(yMin, value);
          yMax = Math.max(yMax, value);
        }
      }
    }
    if (!Number.isFinite(yMin) || !Number.isFinite(yMax)) {
      yMin = 0;
      yMax = 1;
    }
    const ySpan = yMax - yMin || 1;
    const sx = (value) => pad.left + (value - xMin) / xSpan * plotW;
    const sy = (value) => pad.top + plotH - (value - yMin) / ySpan * plotH;
    let paths = "";
    for (const series of payload.series) {
      let d = "";
      for (let index = 0; index < series.values.length; index += 1) {
        const value = series.values[index];
        if (!Number.isFinite(value)) {
          continue;
        }
        const px = sx(x[index] ?? value);
        const py = sy(value);
        d += `${d === "" ? "M" : "L"}${px.toFixed(1)},${py.toFixed(1)} `;
      }
      paths += `<path d="${d.trim()}" fill="none" stroke="var(--mso-focus)" stroke-width="1.5" data-series="${series.name}"/>`;
    }
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="100%" role="img" aria-label="Plot of ${payload.series.map((s) => s.name).join(", ")}">
    <rect x="${pad.left}" y="${pad.top}" width="${plotW}" height="${plotH}" fill="var(--mso-canvas-bg)" stroke="var(--mso-border)"/>
    <line x1="${pad.left}" y1="${pad.top + plotH}" x2="${pad.left + plotW}" y2="${pad.top + plotH}" stroke="var(--mso-fg)"/>
    <line x1="${pad.left}" y1="${pad.top}" x2="${pad.left}" y2="${pad.top + plotH}" stroke="var(--mso-fg)"/>
    <text x="${pad.left + plotW / 2}" y="${height - 8}" text-anchor="middle" fill="var(--mso-fg)" font-size="12">${payload.xLabel ?? payload.series[0].name}</text>
    ${paths}
  </svg>`;
    stage.innerHTML = svg;
    status.textContent = `Plotted ${payload.series.length} series from ${payload.file}.`;
  }
  apply();
  vscode.postMessage({ version: CONTRACT_VERSION, type: "webview/ready" });
})();
